export { default as CNSRegistryABI } from "./CNS_REGISTRY.json";
export { default as ETHRegistrarControllerABI } from "./ETHRegistrarController.json";
export { default as NameWrapperABI } from "./NameWrapper.json";
export { default as ReverseRegistrarABI } from "./ReverseRegistrar.json";
export { default as ReverseRecordsABI } from "./ReverseRecords.json";
export { default as BaseRegistrarABI } from "./BaseRegistrar.json";
export { default as PublicResolverABI } from "./PublicResolver.json";
export { default as WEB3CONTROLLERABI } from "./Web3RegistrarController.json";
export { default as MulticallABI } from "./Multicall.json";
